### ISSUE TITLE
POX fires packetIn events before ConnectionUp - crashes l2_multi

### ISSUE THREAD

**Issue by andiwundsam** [noxrepo/pox#108]
Little bug I just found with STS (https://github.com/ucb-sts/experiments/tree/master/pox_early_packetin).

There is a window between the features_reply and the final barrier_reply in the handshake when POX doesn't consider the switch 'up' (i.e., hasn't yet informed it's listeners of its presence) but already delivers packetIn events. 

(Note that the switch considers the connection to be established after the features_request and can raise any kind of messages).

In combination with openflow_discovery and l2_multi, this can lead to openflow_discovery raising a LinkEvent for a Switch that has not yet seen its connectionUp. This causes l2_multi's handle_LinkEvent to fail (l2_multi.py:436) with a KeyError.

Potential solutions:
- of_01 could dispatch events only for 'up' switches
- topology could validate the state of the switch it receives a PktIn on

**Comment by MurphyMc** [comment]
Hah.  That's ironic since I've in the past complained about switch implementations which send packet-ins before they should yet POX is guilty of the counter-issue (accepting them before it should).

I think your first solution is the right one.  I actually had it in my head that that's what it did already.

This same thing probably applies to events besides PacketIn.  Hmm... I wonder what the best way to fix this is.

Thanks for the catch.  Go STS. :)

**Comment by MurphyMc** [comment]
A note that the event dispatch for of_01 is actually sort of crazy/ugly mostly due to a holdover from very, very early on.  There was some nicer code at some point which never got merged, though it might have been the basis of the dispatch in the datapaths package (for the opposite side of OpenFlow connections).  One might want to check on that or just rewrite it if one were going to take a stab at this.

Other factors one might want to think about:
- Using an ioworker for reading off the wire
- Improving the API for decoding/dispatching extensions
- Making it easier to decode/dispatch multiple OpenFlow versions (possibly this just means factoring out the IO loop from the rest of of_01, which shouldn't be that hard)

**Comment by MurphyMc** [comment]
Note that the above proposal impacts #110

**Comment by MurphyMc** [comment]
Okay, I've merged my experimental patch into dart (85895c73660f16b0b1d25788ba109b9ee5b8189e), and Denys Haryachyy fixed up a couple details.

Connections are slightly more expensive now, but there are some new benefits, and we can readdress things if the extra hit on connect causes problems.

In short, this should be fixed and I'm closing it. :)
