### ISSUE TITLE
How does POX work with mptcp

### ISSUE THREAD

**Issue by buptmuye** [noxrepo/pox#132]
MPTCP is now more and more popular, and I want to do some tests in SDN network using POX. In dart branch, there is MPTCP support, but how to use it?

**Comment by MurphyMc** [comment]
The MPTCP support in POX is simply that when you look at a parsed packet with MPTCP options, at least some of the MPTCP info is available in a Pythonic structure.  What you want to do with this is up to you.

Off the top of my head...

In one sense, I don't think you need to do anything.  MPTCP doesn't require cooperation from the underlying layers in order to work.

If you wanted to do something tricky (like make sure that subflows took alternate paths)... well, any sort of multipath you already might do (e.g., based on hashes of the 5 tuple or a 6-tuple including incoming interface) should work.

If you want to do something MPTCP-specific... I don't think any version of OpenFlow can match on MPTCP subflow information, so you're somewhat limited there.  If you are doing a reactive controller, you can inspect the MPTCP header in an initial packet-in and install narrow table entries, though.
