### ISSUE TITLE
help wanted: find the port to the adjacnet switches (dpid )

### ISSUE THREAD

**Issue by Maryam-Maya-Karimi** [noxrepo/pox#152]
Hi
I have written a method to find the best route. the routes are based on switch dpids. for example it looks like { 00-00-00-00-00-01 , 00-00-00-00-00-02 , 00-00-00-00-00-03 } now I want to install this route in switches. I read that I can install flow on switched by specifying switch dpid by
core.openflow.sendToDPID(dpid, po)
so I don't need to know any thing more about the switch that I am going to install the flow on it.
""but I should know the mac address of adjacent switches and the port that is connected to them to make the msg to be installed in the table.""
for example in switch with dpid 00-00-00-00-00-01 I need to know the port that connect it to 00-00-00-00-00-02.
can you please help me to do this?

**Comment by MurphyMc** [comment]
If you know how the switches connect so that you can compute paths between them, why don't you know the ports?  If you know this because your topology is being read from a file or something, then this file should contain the port numbers too, or my claim is that it is useless.

If you're discovering the topology dynamically (e.g., using POX's discovery component), then port information is available through discovery.

Have you looked at the l2_multi and topo_proactive examples in POX?  They demonstrate doing pretty much what you're talking about.  They use the discovery component to figure out the topology (including ports), compute paths, and install them.

Here's a writeup on how l2_multi works: https://www.mail-archive.com/pox-dev@lists.noxrepo.org/msg01073.html
Here's one on topo_proactive: https://haryachyy.wordpress.com/2014/06/14/learning-pox-openflow-controller-proactive-approach/

In l2_multi and topo_proactive, you can simply replace the _calc_paths() function with your own path computation and it should take care of the rest -- including figuring out which ports to use (it gets them from discovery).  And both of them solve (in different ways) the problem of learning where hosts are (that is, since paths are computed between switches, you somehow need to associate hosts with the switch they connect to in order to glue the whole thing together).

Incidentally, you most certainly do not need to know the MAC address of adjacent switches unless you really want to.

**Comment by Maryam-Maya-Karimi** [comment]
thank you very much

**Comment by matrix69** [comment]
Dear MurphyMc
I find out that I may use it in the method "_get_path" like:
 "path=core.Routing.calculate_route(src, dst)" (which is my method for routing and return a string of dpids as route)
 instead of
 "path = _get_raw_path(src, dst)" (that is an original l2_multi path)
when I print the results here they both show me some thing like:
[00-00-00-00-00-03, 00-00-00-00-00-02, 00-00-00-00-00-01]

but there is a problem.
in "class WaitingPath " in _init_ method when it needs to calculate "self.first_switch = path[0][0].dpid" it gives me an error " 'str' object has no attribute 'dpid'" even when I change the path elements to dpid by str_to_dpid(...) I got the error "" 'int' object has no attribute 'dpid'"" 
I printed my result in _init_ I saw that my path elements will look like 
[('00-00-00-00-00-03', 1, None), ('00-00-00-00-00-06', None, None), (00-00-00-00-00-05, None, 2)]
while the original l2_multi will look like
init [(00-00-00-00-00-03, 1, 2), (00-00-00-00-00-02, 3, 2), (00-00-00-00-00-01, 2, 1)]
while the only change I made was putting my route in _get_path as I mentioned and it seems correct there.
my algorithm calculate route and out put pure string of dpids. can you please help me to put it inside the l2_multi

thank you very much
