### ISSUE TITLE
Minor issues causing statistics messages to fail

### ISSUE THREAD

**Issue by ghost** [noxrepo/pox#16]
**In pox/openflow/libopenflow_01.py:**
Line 2378:

``` python
    if (len(binaryString) < 48 + len(self.match())):
```

Should be:

``` python
    if (len(binaryString) < 48 + len(self.match)):
```

**In pox/openflow/of_01.py:**
Line 193:

``` python
    msg = of.ofp_aggregate_stats_reply()
```

Should be:

``` python
    msg = of.ofp_aggregate_stats()
```

**Comment by MurphyMc** [comment]
The former just looks like a bug.  Fixed.

The latter one is a regression because 01f83795ab316ba8223676c115bcab861d35f170 changed the name of the aggregate stats reply class.  The name was actually purposefully not the name as it appears in the spec, because a decision was made that the names in the spec could be improved (e.g., request/reply messages should explicitly be named with _request and _reply).  Both names should now work.  (The REST of the request/reply class names should be changed to adhere to this.)

I haven't tested, but hopefully this fixes stats messages.  Feel free to reopen if I've goofed. ;)  Thanks for the report!
