### ISSUE TITLE
port_status race condition causing topology discovery failure

### ISSUE THREAD

**Issue by samueljero** [noxrepo/pox#162]
In the current POX code port_status messages are silently dropped during the switch-controller handshake (i.e. while using HandshakeOpenFlowHandlers). Unfortunately, this leads to a race condition where important topology changes can occur between the time that the features_reply message is received---containing a complete list of ports at the moment it was sent---and the time the handshake completes and port_status messages begin to be delivered.

I have observed this bug causing topology detection failure and associated routing failure (when using l2_multi) in a simple mininet tree toplogy. In particular, mininet is still configuring the network when the features_reply message  is sent and some ports aren't added until after that point. port_status messages are sent about these new ports, but POX drops them because the handshake hasn't completed yet. As a result, POX has no idea these new ports exist, so openflow/discovery.py never sends LLDP packets out these ports and no links from them are discovered.

My suggested solution is to collect port_status messages received on a connection prior to the switch-controller handshake completing and defer processing them, and sending port_status events, until the connection completes.

**Comment by MurphyMc** [comment]
The fact that there isn't an explicit setup/negotiation phase is truly a plague.

I don't think I have any better ideas than your proposed solution.

**Comment by MurphyMc** [comment]
Pushed an altered version of your patch.  Thanks!

I want to document something here which is also in the above commit's message:
It might actually make sense to update the ports in the connection's ports collection _before_ raising the ConnectionUp event and simply ignore the port state events, but we don't currently do this.

If we go this route, we should probably even go one step further and alter the ports in the features message.  In essence, we'd hide the fact that these port_status messages ever existed, and instead, we'd fold them into the first view of the ports that most components will ever get: either in the Connection's ports collection (good) or in the features reply (less good, but not unreasonable).  Doing this seems a bit heavy-handed, which is why I haven't done it (yet?).  On the other hand, the current situation is that the ports in the features reply and the initial ports collection are known (to POX) lies (ot at least known to be out of date), which are then immediately corrected... and it seems like it might be nice to just avoid telling the lies in the first place.
