### ISSUE TITLE
Parsing GRE packets using Pox Controller

### ISSUE THREAD

**Issue by xer0xe9** [noxrepo/pox#166]
Hello, I am generating GRE encapsulated traffic on mininet hosts using scapy for my research project, but I came to know lately that PoX cannot parse GRE packets, for handling this issue I need to write a GRE packet class and parser which can parse encapsulated layer2, layer3 and layer4 data from GRE packet. Could someone shed some light as to what steps do I need to follow in order to add a new parser in PoX Controller. Any guideline/suggestion would be highly appreciated.

**Comment by MurphyMc** [comment]
I don't think it should be too hard.  Off the top of my head...

Write a new packet_base subclass which can pack and unpack GRE.  The GRE header will contain the Ethertype of the encapsulated packet.  Look that up in ethernet.type_parsers to get the parser for the encapsulated packet and set that as .next.

Tweak ipv4.parse() so that it knows that IP type 47 (or whatever GRE is) gets handled by your new subclass.

I think that's about it.

I never bothered to do this since I didn't know if any use cases... generally the tunneling is handled by the switch.

**Comment by xer0xe9** [comment]
Thank you very much for this comprehensive response. 

Tunneling is handled by switch on physical host running multiple virtual OSes from different or same tenants, due to some unavoidable issues, I had to simulate this scenario on mininet hosts using traffic generation tools and Virtual IP addresses on Mininet hosts, therefore, I want to write a controller which should act like a GRE gateway i.e., encap/decap traffic only when needed. Thanks again.

**Comment by MurphyMc** [comment]
You can thank me by submitting your GRE patch as a pull request. ;)
