### ISSUE TITLE
When  a switch access POX controller, it appear a  EROOR!!!!!

### ISSUE THREAD

**Issue by Iamshg** [noxrepo/pox#174]
# when i use a switch to access controller.
the controller appear this error?
what is # wrong?
```shg@shg-virtual-machine:~/pox$ python -V
Python 2.7.12
shg@shg-virtual-machine:~/pox$ python pox.py  openflow.of_01 forwarding.l2_learning
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:core:POX 0.2.0 (carp) is up.
ERROR:openflow.of_01:[None 1]: Exception while handling OpenFlow message:
[None 1] ofp_features_request
[None 1]   header: 
[None 1]     version: 1
[None 1]     type:    5 (OFPT_FEATURES_REQUEST)
[None 1]     length:  8
[None 1]     xid:     2
Traceback (most recent call last):
  File "/home/shg/pox/pox/openflow/of_01.py", line 757, in read
    h(self, msg)
TypeError: 'NoneType' object is not callable
ERROR:openflow.of_01:[None 1]: Exception while handling OpenFlow message:
[None 1] ofp_set_config
[None 1]   header: 
[None 1]     version: 1
[None 1]     type:    9 (OFPT_SET_CONFIG)
[None 1]     length:  12
[None 1]     xid:     3
[None 1]   flags: 0
[None 1]   miss_send_len: 128
Traceback (most recent call last):
  File "/home/shg/pox/pox/openflow/of_01.py", line 757, in read
    h(self, msg)
TypeError: 'NoneType' object is not callable
```

**Comment by Maryam-Maya-Karimi** [comment]
How did you call the controller?

**Comment by Iamshg** [comment]
at controller (192.168.1.111) , i exec the cmd 
`python pox.y openflow.of_1 forwarding.l2_learning `
and at the switch(192.168.1.103) at mininet
i exec the cmd 
ovs-controller tcp:192.168.1.111:6633 --detach

**Comment by MurphyMc** [comment]
I don't know; that seems strange. But it's worth noting that your POX seems to be quite old.  You might try with the dart or eel branch.

**Comment by MurphyMc** [comment]
Wait... what?

ovs-controller...?  The name keeps changing, but I think that's the simple controller that's included with OVS for testing purposes.  It looks to me like you are telling the test controller to connect to POX (which is running as a controller in your example).  The test controller is sending POX an ofp_features_request, and POX is complaining because it doesn't handle features requests, because that's something that switches do, and POX is running as a controller here.

I don't know what you're trying to do, but you probably mean to be running OVS as a switch.  That doesn't involve ovs-controller.  Read the OVS installation/configuration documentation.

AFAICT, POX is doing the right thing here, so I'm closing this.
