### ISSUE TITLE
how to ping between host1(connected to contr1) and host2(connected to contr2),in the below topology

### ISSUE THREAD

**Issue by tessythomasrset** [noxrepo/pox#182]
![doubt](https://cloud.githubusercontent.com/assets/25678060/24701078/cad98b70-1a16-11e7-83bc-9318f62b00b4.png)
sir,
i would like to know how to connect between host1(connected to contr1) and host2(connected to contr2),
without having switch to switch connection
thankyou

**Comment by MurphyMc** [comment]
This seems to be a variation of #181.  Again, I struggle to think of any conceivable use case where this is reasonable.  But I think you could do it by...

Disabling in-band control (possibly not necessary).  Configuring s1 to connect to both c0 and c1, so that it accepts commands from both simultaneously and sends packet-ins to both.  Connect two ports on s1 to each other (call them ports 3 and 4)... if s1 is a physical switch, run a jumper between two ports... if it's OVS, you could probably use patch ports.

Now I think the same controller as for #181 would work.  Have all controllers install table entries on all switches which match all packets and send them to controller (output action with OFPP_CONTROLLER virtual port).  When the controller gets a packet-in from one switch, send it as a packet-out to its other connected switch (using OFPP_FLOOD would work here).

**Comment by tessy123** [comment]
hi..thankyou for reply
i made client-server communication with pox1 and pox2,Can i exchange the flow tables between the controllers?..will it be useful,how to proceed??
thankyou

**Comment by MurphyMc** [comment]
It's hard to say, since I don't understand what it is that you're trying to accomplish.

**Comment by tessy123** [comment]
Hi,i need to accomplish multiple controller communication,..i want to run distributed controller in pox..(could not find command to run it,can u pls explain how to run distributed controller in pox)...
so i try to make multiple controllers communicate with socket programming...
