### ISSUE TITLE
recommended way to send packets from hosts to controller

### ISSUE THREAD

**Issue by lordlabakdas** [noxrepo/pox#184]
Hello,
What is the recommended way to send packets from the hosts to the controller?
I am working on an alternate architecture where the hosts gather some intelligence about the network and forward it to the controller. Is it possible for pox to accept messages from the hosts in the network. Could you please provide pointers on how to do this?
I currently tried creating a separate socket for host related data and added it as a pox component as given [here](https://gist.github.com/lordlabakdas/733bca2c570e6a02e94b8cc6047d3cd5). This setup seems to work well with non Mininet originated packets but I get the below error when trying to use a Mininet script.
`Unable to contact the remote controller at 192.168.56.1:6633`

**Comment by MurphyMc** [comment]
This is related to the issue of in-band and out-of-band control in SDNs.  I don't use Mininet anymore, but I *think* that in Mininet, the controller is generally not directly accessible via the Mininet data network (that is, I believe the default assumption is an out-of-band control network).  If that's inconsistent with what you're looking to do, you should see about configuring Mininet so that the controller is accessible to the data network.

If you *are* looking at cases where there's a separate control network, one way to do it would be to have switches send your packets from the host to the controller via OpenFlow packet-ins, but this approach has some pretty serious constraints... I wouldn't try to do it if there was more than a pretty small amount of such packets.

**Comment by lordlabakdas** [comment]
Could you provide any references/pointers as to how to make the host send packetins messages through the switches to the controller?
I do not envision too many messages from the host to the controller other than the occasional drop flow messages.

**Comment by lordlabakdas** [comment]
Got it to work after eventually understanding what you mentioned :) 
I created packet-ins from the host to the controller using scapy originated packets with the payload having information on what action the controller must perform.

**Comment by NadiaMOUAWAD** [comment]
Hello, 
Can you please tell me how did you create the packet-ins to the controller because I need to send a trigger to he controller in order to start an application.

**Comment by MurphyMc** [comment]
In OpenFlow 1.0, any packet arriving at a switch which doesn't match a table entry will be sent to the controller as a packet-in.  The packet may be truncated to some maximum length, though you can control that by adjusting [core.openflow.miss_send_len](https://noxrepo.github.io/pox-doc/html/#the-openflow-nexus-core-openflow) (or just loading the [misc.full_payload](https://noxrepo.github.io/pox-doc/html/#misc-full-payload) component, which does exactly this).

You can also have table entries which explicitly send packets to the controller by using an [output action](https://noxrepo.github.io/pox-doc/html/#output) where the output port is set to the special value OFPP_CONTROLLER.
