### ISSUE TITLE
Mininet hosts fails to ping internet while using l3_learning script for pox controller

### ISSUE THREAD

**Issue by AashavPanchal** [noxrepo/pox#185]
Im trying to ping the internet through the mininet hosts creating the topology using --nat command.
The hosts can connect to the internet while using the l2_learning script while it fails to connect while using l3_learning script,it goes to an infinite loop of flooding ARP requests and there is no reply.
What might be the issue?

![35e241ae-8a67-4c4a-81a8-6c8a268e1568](https://cloud.githubusercontent.com/assets/24518334/25728643/38b3ae16-30e5-11e7-9fa4-ff057b911c80.jpg)

**Comment by MurphyMc** [comment]
I don't use Mininet anymore and haven't really looked at this setup, so I'm just guessing, but...

What is the routing table like on the hosts?  If they're set up to just use a specific interface, that won't be enough... you'll need to have a gateway set for reaching the internet.

**Comment by AashavPanchal** [comment]
![capture1](https://cloud.githubusercontent.com/assets/24518334/25730742/540bcac2-30f4-11e7-8603-0bef268bfab0.PNG)

The routing table on the host shows this.

**Comment by MurphyMc** [comment]
I haven't messed with l3_learning for a long time, but thinking about it a bit more... l3_learning is sort of a funny animal, and I think your use case is just not something it's meant to do.  It could be made to do it with some work, but whether that'd be worth it, I think depends on what exactly you're trying to do...

**Comment by AashavPanchal** [comment]
I'm working on a SDN project and want to fetch a file from mininet hosts.Some of the hosts act as a cache server which uses ARP to send the file to other hosts which would require use of L3_learning for ARP .
I cannot find a reason on why l2_learning works fine with the same topology whereas l3_learning cannot get the traffic to flow through it.

**Comment by MurphyMc** [comment]
If the hosts are sending ARPs, the ARPs will certainly be forwarding by l2_learning...

**Comment by AashavPanchal** [comment]
Why not by l3_learning?

**Comment by MurphyMc** [comment]
For starters, the comment at the top of l3_learning says:
"Keep a table that maps IP addresses to MAC addresses and switch ports.
   Stock this table using information from ARP and IP packets."

You'll never get an IP packet from 8.8.8.8 without sending one to it first (due to the NAT/routing outside of the OpenFlow part of the network).  So the only way you could populate this table entry would be via an ARP.  But you'll also never get an ARP from 8.8.8.8 (or any other Internet address). 
 Thus, you'll never get a table entry for 8.8.8.8.  So you can never send to it.

l3_learning isn't how L3 works on a "normal" network.  It's specifically an example of doing something sort of unusual.  It wouldn't be that hard to make it work, but it won't work out of the box.

**Comment by AashavPanchal** [comment]
Ohkay , thanks a lot for the information.
