### ISSUE TITLE
when i run pox controller its show me error 

### ISSUE THREAD

**Issue by humikahout** [noxrepo/pox#187]
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86

**Comment by MurphyMc** [comment]
As you can see, those log messages are at the INFO level, not error.

[This is discussed in the POX FAQ](https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-Whataretheselogmessagesfromthepacketsubsystem%3F).

**Comment by humikahout** [comment]
How we stop this

**Comment by MurphyMc** [comment]
The FAQ entry has several suggestions.  For example, include "log.level --packet=WARN" on the POX commandline.

**Comment by humikahout** [comment]
I am not able to stop the dhcp message

**Comment by MurphyMc** [comment]
What did you do to try to stop it?

**Comment by humikahout** [comment]
i try to upgrade the pox controller it show me directory is not empty.
fatal: destination path 'pox' already exists and is not an empty directory. a
nd also increase the data length using h1 ping -s 150 h2

**Comment by MurphyMc** [comment]
There is a FAQ entry specifically on the problem you're having, which is what I was referencing and mentioned an example from earlier.  Specifically, it suggests:

1. Ignore it unless it's actually causing a problem for you (because your application requires these packets to be parsed correctly).
2. Turn the packet subsystem's log level to warning (log.level --packet=WARN).
3. Install a flow to send the entirety of relevant packets to the controller (an ofp_action_output to OFPP_CONTROLLER will default to doing this).
4. Tell the switch to send complete packets to the controller on table misses (an easy way is to simply invoke the misc.full_payload component).

The one I mentioned about was the second one.  To do this, you change your commandline to be something (for example):
`./pox.py log.level --packet=WARN forwarding.l2_learning`


As for the issue trying to update your controller, you should probably refer to the git manual.  But if you've made the POX clone recently, you can probably update to the eel branch with something like `git checkout eel`.  It won't work if you've modified files, in which case, I again refer you to the git documentation.

**Comment by humikahout** [comment]
Thanks a lot its help me... 
Log.level --packet = warn
Its stop the log message
