### ISSUE TITLE
hosts on different networks are unreachable using L3_learning 

### ISSUE THREAD

**Issue by xer0xe9** [noxrepo/pox#190]
Hello,

I have following topology specification in mininet:

![image](https://user-images.githubusercontent.com/5043463/27202505-5dc07a8c-523b-11e7-9460-7fc18345d72a.png)
 
I am running l2_learning on s1, s2, s4 and l3_learning on s3.
l2_learning works but when I try to ping h6 from h1, Host is Unreachable.

setting default gateway on hosts:
    h1.cmd("route add default gw 10.0.0.1")
    h2.cmd("route add default gw 10.0.0.1")
    h3.cmd("route add default gw 192.168.66.1")
    h4.cmd("route add default gw 192.168.66.1")
    h5.cmd("route add default gw 20.0.0.1")
    h6.cmd("route add default gw 20.0.0.1")

While setting static ARP entries works only for local network.

Hosts on different networks are not reachable and l3_learning module keeps on flooding ARP request:
DEBUG:forwarding.l3_learning:3 1 ARP request 10.0.0.101 => 10.0.0.1
DEBUG:forwarding.l3_learning:3 1 flooding ARP request 10.0.0.101 => 10.0.0.1

Can you please point out what I am doing wrong and elaborate on the solution. 

Thanks.

**Comment by MurphyMc** [comment]
Is that l2_learning on s1, s2, s3, and l3_learning on **s4**?

**Comment by MurphyMc** [comment]
Well... l3_learning isn't a router.  There are no gateways here.  When your hosts try to find the L2 address for their default gateways, there's nobody there.  Set all your hosts to have a default which simply uses the port to the switch -- not a gateway IP.  The reasoning here is along the lines of... you say "hosts on different networks", but as far as l3_learning is concerned, _there are not different networks_.  Because it's not a router.  It's a weird L3 learning switch thing.  So what you have to do is convince the hosts that there are not different networks either.  By just setting all addresses to use a port with no gateway -- exactly like it's usually set up for only a "local subnet".

An alternate approach would be... l3_learning also has the --fakeways=IP1,IP2,... option.  Which adds "fake gateway" addresses which l3_learning will respond to ARPs for.  You could try this.  So after l3_learning on the commandline, add --fakeways=10.0.0.1,192.168.66.1,20.0.0.1.  Without really thinking about it, I'm not sure this will work in your scenario.  But you could give it a shot. :)  The idea behind it is that... all l3_learning needs from the host is for the host to give it the packet.  By just responding to an ARP, it should get the host to do it.  The MAC address will then be "wrong" (it'll be the useless address to the "fakeway", not the address to the destination host), but if I remember right, l3_learning then rewrites the L2 destination with the one matching the destination L3 address that it has gotten via learning anyway.

**Comment by precociouss** [comment]
Yes, 
./pox.py log.level --DEBUG pox.forwarding.l3_learning --fakeways=10.0.0.1,192.168.66.1,20.0.0.1 openflow.of_01 --port=6635

mininet> h1 ping h6
PING 20.0.0.3 (20.0.0.3) 56(84) bytes of data.
64 bytes from 20.0.0.3: icmp_seq=1 ttl=64 time=96.5 ms
64 bytes from 20.0.0.3: icmp_seq=2 ttl=64 time=0.676 ms
64 bytes from 20.0.0.3: icmp_seq=3 ttl=64 time=0.118 ms

It is working. 

Thanks.

**Comment by xer0xe9** [comment]
Yes,
./pox.py log.level --DEBUG pox.forwarding.l3_learning --fakeways=10.0.0.1,192.168.66.1,20.0.0.1 openflow.of_01 --port=6635

mininet> h1 ping h6
PING 20.0.0.3 (20.0.0.3) 56(84) bytes of data.
64 bytes from 20.0.0.3: icmp_seq=1 ttl=64 time=96.5 ms
64 bytes from 20.0.0.3: icmp_seq=2 ttl=64 time=0.676 ms
64 bytes from 20.0.0.3: icmp_seq=3 ttl=64 time=0.118 ms

It is working.

Thanks.

**Comment by MurphyMc** [comment]
Glad to hear it.
