### ISSUE TITLE
l2_multi behaves unexpectedly when facing a syn flood

### ISSUE THREAD

**Issue by fredericoschardong** [noxrepo/pox#197]
Hi,

I have a medium size scenario and was facing some strange problems with `l2_multi` (unrelated to my [previous question](https://github.com/noxrepo/pox/issues/196)). I reduced it to this small example and called pox with `./pox.py openflow.of_01 --port=6633 forwarding.l2_multi openflow.discovery --eat-early-packets openflow.spanning_tree --no-flood --hold-down` on eel branch.

    #!/usr/bin/python

    from mininet.net import Mininet
    from mininet.log import setLogLevel, info
    from mininet.cli import CLI
    from mininet.node import RemoteController

    def intfOptions():
        net = Mininet()
        net.addController(RemoteController('c0', ip='127.0.0.1', port=6633))

        h1 = net.addHost('h1')
        h2 = net.addHost('h2')

        s1 = net.addSwitch('s1')
        s2 = net.addSwitch('s2')
        
        net.addLink(h1, s1)
        net.addLink(h2, s2)
        net.addLink(s1, s2)

        net.start()
        CLI(net)
        net.stop()

    if __name__ == '__main__':
        setLogLevel('info')
        intfOptions()

Then I run `hping3 -i u1 -S -p 80 10.0.0.1` on h2, which sends TCP packets with the SYN flag on them. Strangely enough, the controller starts poping out error messages, but I see a fraction of the traffic getting to h1.

I get a bounch of `ERROR:forwarding.l2_multi:3 paths failed to install` and a few seconds later `OFPBRC_BUFFER_UNKNOWN` errors. Almost complete log (had to remove some duplicated lines) up to when I close mininet is [here](https://pastebin.com/T5XrNsei). If I change the remote controller for OVSController it works as expected. Thank you for your help.

**Comment by MurphyMc** [comment]
Reactive designs like l2_multi won't work well under SYN flood.  Each packet looks like a new flow, the switch will send them to the controller, the controller will try to install entire paths.  The control channel between switches and the controller is probably rate limited, links to controllers may be bottlenecks, the controller itself is never going to be fast enough to keep up with computing a path for every single packet, and the amount of traffic is magnified both by OpenFlow encapsulation and because the controller will likely send table entries to multiple switches.  Etc., etc.  Fully reactive designs like l2_multi aren't a reasonable way to write a controller for many situations.

That said, one could probably improve it for this case a fair amount.  Right now it [tries to install exact matches for every connection](https://github.com/noxrepo/pox/blob/eel/pox/forwarding/l2_multi.py#L383).  Instead, create entries for every src/dst IP or (probably better yet) Ethernet pair.  Something [like l2_pairs does](https://github.com/noxrepo/pox/blob/eel/pox/forwarding/l2_pairs.py#L62).
