### ISSUE TITLE
Is this the place to discuss about how to build using POX API?

### ISSUE THREAD

**Issue by wuming79** [noxrepo/pox#201]
Hi, 

I'm trying to look for a POX SDN forum but looks like this is the only place to post? 

Like to ask if this is the right place to discuss about how to build using POX API and other questions such on how SDN really functions using POX? COntroller can send commands to change flow table of switch but can switch send message back to controller? Are there any examples on how to write a script to do that?

**Comment by MurphyMc** [comment]
I think this is as good a place as any since the pox-dev mailing list has been unreliable at best for a long while.

The switch does send back certain messages.  Since POX implements OpenFlow 1.0, they're all defined in the OpenFlow 1.0 spec.  Well, there are some which are extensions from Open vSwitch too.  But mostly in OpenFlow 1.0.

POX contains many examples, and the [POX wiki manual](https://openflow.stanford.edu/display/ONL/POX+Wiki) contains lots of information.
