### ISSUE TITLE
A topology visualizer for pox 

### ISSUE THREAD

**Issue by Hrish1** [noxrepo/pox#204]
Hi there!, 
wouldn't it be nice if pox allowed the users to have a bird's-eye view of what it's controlling? at least a very trivial picture of the topology that it maintains. 

the use might be limited bcoz the simulators would give you exactly that and also let you connect to pox. But a topology graph can add to the UI.

**Comment by MurphyMc** [comment]
There are multiple options for this already if you're using OpenFlow and the OpenFlow discovery component (and maybe the host tracker component too).

1. POX includes the misc.gephi_topo component which hooks it up to the awesome [Gephi graph viz platform](https://gephi.org/).  Then you can use any of Gephi's abilities in order to visualize.  There's a mention of it [in the POX manual](https://web.archive.org/web/20160423221312/https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-misc.gephi_topo), and here's a [pretty detailed blog post](http://www.brianlinkletter.com/visualizing-software-defined-network-topologies-using-pox-and-gephi/) about setting it up.
2. [POXDesk](https://github.com/MurphyMc/poxdesk) is a web-based frontend framework for POX.  It comes with a number of applications which includes a topology viewer.  Here's a [screenshot](http://7xnzbp.com2.z0.glb.qiniucdn.com/wp-content/uploads/2014/10/pox-web-gui.jpg) where you can see the topology viewer showing the running topology (which is a really simple one).
3. The development version of POX (fangtooth) has the [openflow.discovery:graph](https://github.com/MurphyMc/pox/blob/5216d18641aee8ecd3f9f314d1adcd49cf78b3e5/pox/openflow/discovery.py#L489) component, which can automatically export a .dot file with the discovered topology.  There's even a little script in the documentation which details how to use it for a live view of the topology.

**Comment by Hrish1** [comment]
will it be redundant work creating another visualizer component using some different framework?
Like I was thinking of using netjson

**Comment by MurphyMc** [comment]
I guess it depends on what it offers that the existing ways don't and, specifically, whether it fulfills some need of yours that the others don't and couldn't easily be made to.
