### ISSUE TITLE
pypy, module not found.

### ISSUE THREAD

**Issue by yzexeter** [noxrepo/pox#207]
Hi, I am trying to use pypy to run my pox scripts, which is located in .../pox/ext/ 
My running command is "./pox.py mymodule", where I replace the module names with mymodule because it cannot work for all modules I write. This can work for all pox built-in modules, like forwarding.l2-learning.
The prompt message is "Module not found: ..."
However, "python ./pox.py mymodule" with built-in python interpreter works. I am wondering what is happening and what I miss to launch my script with pypy. Shall I do something like register or install script in pypy and how can I do it?
It is said pypy may be faster than CPython. That is why I am doing this.

Also, I shall add that I am using anaconda virtual environment python=2.7 to run it. 
Pox verison eel.
OS is Ubuntu 16.04LTS

**Comment by MurphyMc** [comment]
I think that POX may be working fine and that this may be a case of a confusing error message.  Specifically, my guess is that POX is correctly trying to load mymodule, but mymodule itself is importing another module which you have installed for CPython, but not for Pypy.  That is, the error message is telling you the problem is with finding mymodule, but it's *actually* a problem finding something *used by* mymodule.

You can do a few things which may help straighten things out.  First, try `pypy pox.py skeleton --foo`.  This should load the ext/skeleton.py component.  If this works, then the stuff that POX does in order to load out of `ext` would seem to be working with Pypy.

Next, try `pypy pox.py --verbose mymodule` and see if you get a more helpful error message.

Finally, look through your imports in mymodule.  If you have any non-standard ones, they probably need to be installed for Pypy or PyPy's PYTHONPATH/sys.path needs to be updated to include them or whatever.  The best course of action here may depend on exactly what these modules are and how they were installed.  For example, you may want to install/run pip via pypy and then use the pypy pip to install packages.  Or... I think you can create a pypy virtualenv which should probably take care of this stuff for you, but I'm not a big virtualenv user.

**Comment by yzexeter** [comment]
@MurphyMc  Thank you. This makes sense. I do have extra lib to import which is only installed in anaconda environment, like pandas, numpy. Pypy can start ext/skeleton meaning it can load components under ../ext. I will try installing those in pypy. Another thing is in my case --verbose does not show extra information, but this may not be the issue of POX.

**Comment by MurphyMc** [comment]
If I recall correctly, there was something different about the way that Pypy reports this type of error and the way that CPython does, which results in POX handling it well for CPython but gives an ambiguous message for Pypy.  It seems like in the latter case, POX could at the least hint that the problem might be with a dependency rather than the named module itself...

**Comment by yzexeter** [comment]
I can't agree more. Only outputting "module not found" is very ambiguous. In fact, what you mentioned happens in many other libraries or modules. I got stuck in some similar situations where the actual errors are quite different from the "hints". It may take some time to fix the message prompt.

**Comment by MurphyMc** [comment]
There was actually a comment in the source code suggesting that someone should check whether the workaround for Pypy was still necessary after Pypy 2.0, and... it looks like maybe it isn't.  So I've removed the special case, and Pypy now has the same (more helpful) error messages as CPython.  We'll have to wait and see if this breaks something else. :)

It's in the fangtooth branch (which is currently only in my fork, but will make it into the official one at some point), so I'm going to call this fixed?

(For reference, it's MurphyMc/pox@4855525180d83a9b1dc0c628c2afa9f140f0d492)

**Comment by yzexeter** [comment]
Yes, sure. Thank you for helping me with this.

**Comment by EngHassanJ** [comment]
I have go through what you mention above , after installing pypy 
I got this message : 

pypy pox.py --verbose mymodule
POX 0.3.0 (dart) / Copyright 2011-2014 James McCauley, et al.
Module not found: mymodule

any recommendation ?

**Comment by EngHassanJ** [comment]
also i fix the code that mention in link above but still have the problem

**Comment by MurphyMc** [comment]
mymodule is a component that the original poster was creating -- it's not a component that ships with POX.  For a list of components that come with POX, you might start by looking at the POX manual.
