### ISSUE TITLE
Set l2_learning flow-entries to have priority equal to OFP_DEFAULT_PRIORITY

### ISSUE THREAD

**Issue by Celyn1** [noxrepo/pox#216]
My setup includes Pox running l2_learning and an OVS switch. All flow-entries in the switch are set with priority=65535 but the value of OFP_DEFAULT_PRIORITY=32768. How do I set the priority on the flow-entries to OFP_DEFAULT_PRIORITY?

**Comment by MurphyMc** [comment]
If I remember right, l2_learning always installs exact matches, which always get high priority -- there's no way to make them otherwise (in OpenFlow 1.0, anyway).

I think if you run l2_pairs instead (which only matches on L2 addresses), you'll find that the priority is adjustable.

**Comment by Celyn1** [comment]
Thanks, if I modify l2_learning.py and add the line msg.priority=of.OFP_DEFAULT_PRIORITY, before each line where a flow-entry is set: self.connection.send(msg), the flow-entries still come out with maximum priority. I'll use l2_pairs instead.

**Comment by MurphyMc** [comment]
Right.  Exact matches always matching at high priority is something the switch does.  IIRC, an addendum to the OpenFlow 1.0 spec clarified that this was the expected behavior.

You could also modify l2_learning to not install exact matches.  Instead of forming a match with ofp_match.from_packet() [as done here in l2_learning](https://github.com/MurphyMc/pox/blob/fangtooth/pox/forwarding/l2_learning.py#L169), just set dl_src and dl_dst to the values in the packet [similar to as is done in l2_pairs](https://github.com/MurphyMc/pox/blob/fangtooth/pox/forwarding/l2_pairs.py#L62).  It's been long enough that I wouldn't swear that's 100% of what it'd take, but that's the basic idea.  You should get per-MAC-pair table entries (which is what l2_pairs does).  Since the rest of the fields are wildcarded, priorities should work for them.
