### ISSUE TITLE
SDN POX Controller PortStat

### ISSUE THREAD

**Issue by simounical** [noxrepo/pox#228]
Hi everyone, I'm trying to write some code for a personal project. I'm using
def _handle_portstats_received (event):
  stats = flow_stats_to_list(event.stats)
  log.debug("PortStatsReceived from %s: %s", 
    dpidToStr(event.connection.dpid), stats) 

to get statistics from port.

In my topology there are 3 switches, but I'd like to get the information just from Switch#1. How can I do that? The code above prints statics from all switches.

Thank you

**Comment by simounical** [comment]
@MurphyMc

**Comment by MurphyMc** [comment]
As [mentioned in the manual](https://noxrepo.github.io/pox-doc/html/#openflow-events-responding-to-switches), the events generally have a `.connection` and a `.dpid` property, either of which can be used to help differentiate between events raised by different switches.  Additionally, you could add the event listener to a particular connection (in the connection up handler) rather than to the OpenFlow nexus (which is what I assume you're doing), and it'll only fire for that connection.
