### ISSUE TITLE
Module not found: DEBUG

### ISSUE THREAD

**Issue by rashmitajolly** [noxrepo/pox#233]
While running 
./pox.py log.level   DEBUG  l2_learning
command it says   Module not found: DEBUG

**Comment by MurphyMc** [comment]
DEBUG is an argument to the `log.level` component, so it needs a `--` in front.  Also, `l2_learning`'s full name is `forwarding.l2_learning`, so that probably needs adjustment.

```
./pox.py log.level --DEBUG forwarding.l2_learning
```

Better yet, if you're using  recent version of POX, you can replace `log.level` with `samples.pretty_log` and get color logs.

You might want to skim through the [POX Manual](https://noxrepo.github.io/pox-doc/html/).

**Comment by rashmitajolly** [comment]
Thanks for the help.
