### ISSUE TITLE
POX Controller Web Console

### ISSUE THREAD

**Issue by Maziar662000** [noxrepo/pox#248]
Dears,
I am new to POX. I implemented POX on Ubuntu, and now I am wondering whether there is a web console, like that of FloodLight, for POX also or not?

**Comment by MurphyMc** [comment]
Not really.

POX isn't really so much of a controller as a controller framework.  So it doesn't so much have a web console as it has a little bit of a web framework.  POX itself has several components for working with the web, and [POXDesk](https://github.com/MurphyMc/poxdesk) is a framework for developing web-based GUIs which has some examples.  But there's no singular web UI since there's no singular POX functionality.

**Comment by Maziar662000** [comment]
Thank you for your fast reply.
I am going to implement a component on POX for fault tolerance on switch level so that when a switch gets failed the hosts connected to that switch would be migrated to another switch. Would you please shed a light on this for me (any link or information regarding the implementation such a component)?
Also, if it is better to choose another controller please give me your suggestions.
Thanks in advance.

Best regards,
________________________________

**Comment by MurphyMc** [comment]
I think there's too broad of a space of problems/solutions here for me to be able to comment reasonably.

But good luck!
