### ISSUE TITLE
Redirect traffic after changing host IP address in Mininet 

### ISSUE THREAD

**Issue by MohsenBs** [noxrepo/pox#284]
Hi 
Good day 
Your help here is much appreciated

I am using Meininet install on Ubuntu 20.04

h1 as tcp server ( using iPerf )
h2 h3 h4 clients

if change IP for h1 (server) 
- mininet> h1 ifconfig h1-eth0 20.0.0.60 netmask 255.255.255.0

-  How we can redirect  h2 h3 h4 clients' traffic without losing concoction ?  or Mapping 
-  is Pox have components to hand it? or Mapping 
- Does any command line in mininet can handle it?
- any solution or something to do?

Please guide me 

Best Regards 

<img width="167" alt="pic" src="https://user-images.githubusercontent.com/117582476/203144498-d7576812-fb82-433b-9443-bfb071fd755d.png">

**Comment by MurphyMc** [comment]
I can't think of a way to do this with any of POX's standard components.  This would seem to be an unusual use case.

You could write a component to help, but it's not clear how it should work.  Again, because this seems like an unusual thing to do/want.  Maybe you could explain your use case further.
