### ISSUE TITLE
Small improvement in spanning_tree module

### ISSUE THREAD

**Issue by alexjbs** [noxrepo/pox#52]
A good (altough small) improvement on spanning tree module would be blocking flood on all switch ports as soon as it connects.

The module, after calculating the tree,  already unblocks ports that belongs the tree or are connected to hosts.

My sugestion is to put the code below somewhere in the _reset function which handles "ConnectionUp" events.

def _reset (event):

  # Configure all switch ports to NO_FLOOD

  for p in event.connection.ports.itervalues():
    if p.port_no < of.OFPP_MAX:
      pm = of.ofp_port_mod( port_no=p.port_no,
                               hw_addr=p.hw_addr,
                               config = of.OFPPC_NO_FLOOD,
                               mask = of.OFPPC_NO_FLOOD )

**Comment by MurphyMc** [comment]
Thanks for the input!

Has this been tested?  It has been a while since I've really looked at this portion of the spanning_tree logic, but if I remember right... the first time any link is discovered, it will go through all of the ports.  For the edge ports -- which I think will appear to be all of them except for the single one that has had a link discovered so far -- it will turn flooding back on.  So it seems like we may actually need to add a (per-switch?) timer which inhibits that behavior to get the desired result.

Another thing I'd been thinking about to improve spanning_tree/discovery is a high-priority packet_in handler which just eats packets on a switch until a discovery cycle has completed.

(Both of these should probably be optional...)

**Comment by alexjbs** [comment]
First, sorry for not having a pull request ready here at git. I'm new to this.
I have this implemented (just as sugested in pox-dev) and working. Te identation here was lost somehow.

Second, only now I saw your changes from two days ago in spanning tree module.
And it has some degree of impact in my sugestion, as just after a switch connects we modify its ports flags, meaning a feature request should be done following that in order to keep pox core up to date.

Anyway, the spanning tree module has two handlers: one for "ConnectionUp" events that just clears the list of previous port states ( _prev ). And the second for "LinkEvent" from discovery that actually updates spanning tree ( _handle ) and.

It does make sense to block broadcast on all switch ports as soon as it connects to the controller, so we avoid loops in the network while discovery module finds the links adjacency and spanning tree module calculates the broadcast tree.

**Comment by MurphyMc** [comment]
I agree that it makes sense to block floods on connection in many cases.  My concern is that I'm not sure your proposed patch does it that effectively.  While it does it when the switch first connects, I think _handle() will actually undo most of it the first time any link is discovered -- ports with as-yet undiscovered links will look like edge ports temporarily, so they'll get flood enabled.  When the links _are_ discovered, they'll have flood turned back off, but the whole point was to not have it turned on in the first place.

**Comment by alexjbs** [comment]
Let me clarify the reason I modified the spanning tree module with that code: I'm running POX on a mininet vm in my netbook which has an atom processor. 
My simple 4 switch mesh network just turned into useless hot packet soup as soon as switches connected. 

The time discovery takes to calculate adjacency links and spaning_tree to block flood was long enough to keep the processor busy just with the looping packets. 
Too sad such limited resources being defeated by a couple of loops in my virtual network.

 So, start blocking broadcast packets at the very first time a switch goes up on network was the solution for my first quest into SDN world.  :-)

**Comment by MurphyMc** [comment]
Sure, I understood the reason.  My concern was that the change you specified wasn't really as dramatic as it should be to ensure the behavior you want.  As a silly but minimal example, imagine two switches with three links connecting them.  The switches connect and you turn off flooding on all ports.  When the first link is discovered, the spanning tree is updated at which point _flooding will be turned on for the second and third links_ because those links haven't been discovered yet and appear to be edge ports.  This creates a loop.

To combat that problem, I've added the --hold-down option to spanning_tree, which prevents the enabling of flooding until all links have had the chance to be discovered.

Also, the functionality you wanted has been added in the above commit -- enable it with --no-flood.

(The safest invocation is openflow.spanning_tree --no-flood --hold-down.)

**Comment by alexjbs** [comment]
Great! Yes, you're right. In that case a loop will occur. I couldn't manage to have multiple links connecting two switches in mininet. So I did not face that problem in my tests.
I think discovery and spanning tree should work more integrated, so as new connections with ports not yet checked by discovery should remain flood blocked by spanning tree.
Thanks!

**Comment by alexjbs** [comment]
Just to inform, when I exit mininet and the connections are closed an OFPT_ERROR is raised by openflow.of_01. Following details:
[00-00-00-00-00-02 1] Error: type: OFPET_PORT_MOD_FAILED (4)
[00-00-00-00-00-02 1] Error: code: OFPPMFC_BAD_HW_ADDR (1)

**Comment by MurphyMc** [comment]
Yup, this happens.  Without having really looked at it, I think this is just a generic consistency problem caused when the switches are torn down.  The controller temporarily has a different idea of which ports a switch has than the switch does.  In the general sense, there isn't anything to be done about this, and in the practical sense, I don't think this actually causes any problem.

One thing which _might_ help would be to tweak openflow.discovery.Discovery._delete_links() so that it first adjusts the adjacency list, and _then_ raises the events (e.g. turn it from one for loop into two for loops), but that's just off the top of my head.
