### ISSUE TITLE
any way of getting the port status using POX

### ISSUE THREAD

**Issue by nomorecaddy** [noxrepo/pox#87]
wondering if there is a method to get the link up/down status of a given port on a given openflow switch managed by POX.  even better if there was a webservice method for the same.

thanks!

**Comment by MurphyMc** [comment]
The latest port info we have should always be stored in a Connection's .ports attribute.

The webservice method list_switches returned some port info previously, but not flags like up/down.  I've just pushed a pretty trivial improvement so that it does.  If you run pox with the web and openflow.webservice components, you can now do something like:

```
[openflow]$ curl -X POST -d '{"method":"get_switches","id":3}' http://127.0.0.1:8000/OF/
{"result": [{"n_tables": 254, "ports": [{"hw_addr": "16:d3:0f:dc:61:81", "port_down": true, "link_down": true, "name": "s1-eth1", "port_no": 1}, {"hw_addr": "56:84:db:97:6e:cd", "name": "s1-eth2", "port_no": 2}, {"hw_addr": "0a:b5:fb:db:ab:4b", "name": "s1", "port_no": 65534}], "dpid": "00-00-00-00-00-01"}], "id": 3}
```

Note the port_down and link_down members which correspond to the port state and config flags.  Currently these will only be present when the flags are set.

**Comment by nomorecaddy** [comment]
cool, thanks.  I didn't see that response in betta, so perhaps I should git the latest version.  by 'flags are set', do you mean the switch must provide this info via flags?

**Comment by MurphyMc** [comment]
"get_switches" from the webservice should exist in betta, but the extended port info is only in carp (and only as of this morning).

By the "flags are set" thing I just meant that if, for example, the OFPPS_LINK_DOWN flag is 0, there will be no "link_down" entry in the port entry returned from get_switches.  Only if OFPPS_LINK_DOWN flag is 1 will "link_down" appear in the result (thus, if it exists, the value should always be true).

**Comment by nomorecaddy** [comment]
works great.  thanks!
